[server]
host = "0.0.0.0"

[node]
driver-implementation = "chrome"
# Ta opcja jest kluczowa. Zmusza węzeł do zarejestrowania się z adresem hosta, a nie wewnętrznym IP.
host = "localhost"
port = 5555

[distributor]
host = "localhost"

[sessionqueue]
host = "localhost"
