profile.default_content_setting_values.geolocation=1
profile.managed_default_content_settings.geolocation=1
profile.default_content_setting_values.notifications=1
intl.accept_languages=es_ES
download.default_directory="DownloadFolder"
download.prompt_for_download=false
download.directory_upgrade=true
credentials_enable_service=false
profile.password_manager_enabled=false
profile.password_manager_leak_detection=false
password-store=basic
