browser.download.folderList=2
browser.download.dir=${DownloadPath}
browser.download.useDownloadDir=true
browser.download.manager.showWhenStarting=false
browser.helperApps.neverAsk.saveToDisk=application/csv,text/csv,text/plain,application/octet-stream,application/msword,application/vnd.ms-excel,application/pdf
webSocketUrl=true
media.navigator.permission.fake_permissions=true
permissions.default.microphone=1
permissions.default.camera=1
geo.enabled=true
permissions.default.geo=1
geo.provider.use_corelocation=true
geo.prompt.testing=true
geo.prompt.testing.allow=true
dom.webnotifications.requestPolicy=0
dom.push.enabled=true
dom.webnotifications.enabled=true
permissions.default.desktop-notification=1
media.getusermedia.insecure.enabled=true
media.devices.unfocused.enabled=true
gfx.webrender.software=true
layers.acceleration.disabled=true
browser.tabs.remote.autostart=false
media.webrtc.hw.h264.enabled=true
media.getusermedia.screensharing.enabled=true
media.navigator.permission.disabled=true
media.navigator.streams.fake=true
media.autoplay.default=0
media.peerconnection.video.h264_enabled=true
media.getusermedia.audio.enabled=true
media.getusermedia.camera.fake.force=true
media.getusermedia.camera.off_while_disabled.enabled=false
se:downloadsEnabled=true