browser.download.folderList>2
browser.download.dir>${DownloadPath}
browser.download.useDownloadDir>true
browser.download.manager.showWhenStarting>false
browser.helperApps.neverAsk.saveToDisk>application/csv,text/csv,text/plain,application/octet-stream,application/msword,application/vnd.ms-excel,application/pdf
webSocketUrl>true