browser.download.folderList>2
browser.download.dir>${DownloadPath}
browser.download.useDownloadDir>true
browser.download.manager.showWhenStarting>false
browser.helperApps.neverAsk.saveToDisk>application/csv,text/csv,text/plain,application/octet-stream,application/msword,application/vnd.ms-excel,application/pdf
webSocketUrl>true
media.navigator.permission.disabled>true
media.navigator.streams.fake>true
media.navigator.permission.fake_permissions>true
permissions.default.microphone>1
permissions.default.camera>1
geo.enabled>true
permissions.default.geo>1
geo.provider.use_corelocation>true
geo.prompt.testing>true
geo.prompt.testing.allow>true