# --------------------------
# COMMON
# --------------------------
headless>false
start-maximized>true
disable-gpu>true
window-size>900,900
incognito>false
guest>false
use-fake-ui-for-media-stream>true
use-fake-device-for-media-stream>true
disable-notifications>false
no-sandbox>true
disable-dev-shm-usage>true
enable-managed-downloads>true
credentials_enable_service>false
profile.password_manager_enabled>false
disable-password-manager-reauthentication>true
disable-save-password-bubble>true
reduce-security-for-testing>true
password-store>basic
use-mock-keychain
#Ustawienia lokalne, psujace wykonanie w gridzie
local.user-data-dir>C:/Temp/chrome-profile-${threadId}

# --------------------------
# CHROME
# --------------------------

# --------------------------
# EDGE
# --------------------------

# --------------------------
# FIREFOX
# --------------------------