headless>false
start-maximized>true
disable-gpu>false
window-size
incognito>false
use-fake-ui-for-media-stream>true
use-fake-device-for-media-stream>true
disable-notifications>false
enable-system-notifications>true
enable-automation>false
#disable-features=PasswordLeakDetection>true
guest>
proxy-server>
user-agent>
no-sandbox>true
disable-extensions>
enable-logging>
disable-infobars>
remote-debugging-port>
log-level>
disable-software-rasterizer>
accept-language>
lang>
whitelisted-ips>
host-rules>
force-device-scale-factor>
mute-audio>
disable-web-security>
app-banner>
proxy-pac-url
load-extension>
user-data-dir>
data-path>
media-cache-size>
app>
