headless>false
start-maximized>false
disable-gpu>true
window-size>1600,900
incognito>false
use-fake-ui-for-media-stream>true
use-fake-device-for-media-stream>true
disable-notifications>true
no-sandbox>true
disable-dev-shm-usage>true
#user-data-dir>C:/Temp/chrome-profile-${threadId}